# Generated by Django 5.0.6 on 2024-08-01 16:02

import app.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_key_user_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='硬币数量'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='文件名')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('file', models.FileField(upload_to=app.models.file_directory_path)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_files', to='app.user', verbose_name='创建者')),
                ('shared_with', models.ManyToManyField(related_name='shared_files', to='app.user', verbose_name='共享用户')),
            ],
        ),
    ]
